[workspace]
members = [
	"christmas-tree", "day03",
	"day01", "day10", 
	"day02",
	"day03",
	"day04", "day05", "day06", "day07", "day08", "day09", "day11", "day12", "day13", "day14", "day15",
]

resolver = "2"
