[package]
name = "day17"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
christmas-tree = { version = "0.1.0", path = "../christmas-tree" }
glam = "0.24.2"
memoize = "0.4.1"
ndarray = "0.15.6"
