[package]
name = "day25"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
christmas-tree = { version = "0.1.0", path = "../christmas-tree" }
rand = "0.8.5"
