[package]
name = "day16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
christmas-tree = { version = "0.1.0", path = "../christmas-tree" }
either = "1.9.0"
glam = "0.24.2"
rayon = "1.8.0"
